services:
  - type: web
    name: tradebricks
    env: static
    buildCommand: npm run build:render
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
    routes:
      - type: rewrite
        source: /strategy-guide
        destination: /index.html
      - type: rewrite
        source: /editor
        destination: /index.html
      - type: rewrite
        source: /editor/.*
        destination: /index.html
      - type: rewrite
        source: /strategy-guide/.*
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html
